-- =============================================================================
--  Copyright (c) 2026 Nyx Software, Inc.  All rights reserved.
--
--  CodeDistill
--
--  Property of Nyx Software, Inc., provided under a dual license: the GNU Affero General
--  Public License v3.0 (see the LICENSE file) and, separately, a commercial
--  license available from Nyx Software, Inc. Use outside the terms of one of those
--  licenses is prohibited.
--
--  SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Nyx-Commercial
-- =============================================================================

-- v0.11.x — project brain (glass-box Phase 5, slice 5.2).
--
-- The KB grows into the LLM context substrate. Each entry gains a "kind" so the
-- brain has structure: architecture | convention | decision | reference
-- (reference = the default — what every existing entry already is). The MCP
-- get_project_brain tool bundles the structured brain (architecture/conventions/
-- decisions) so the agent builds context-rich instead of guessing.
ALTER TABLE knowledge_entries ADD COLUMN kind TEXT NOT NULL DEFAULT 'reference';
