// =============================================================================
//  Copyright (c) 2026 Nyx Software, Inc.  All rights reserved.
//
//  CodeDistill
//
//  Property of Nyx Software, Inc., provided under a dual license: the GNU Affero General
//  Public License v3.0 (see the LICENSE file) and, separately, a commercial
//  license available from Nyx Software, Inc. Use outside the terms of one of those
//  licenses is prohibited.
//
//  SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Nyx-Commercial
// =============================================================================

package licensing

import "encoding/hex"

// publicKeyHex is the MASTER Ed25519 license-signing PUBLIC key. The private
// half lives outside the repo (generated by `licensegen keygen`), never
// ships, and NEVER goes online — it hand-signs Enterprise licenses.
// Rotating the key invalidates every issued license, so don't — issue a v2
// scheme alongside instead if it ever leaks.
const publicKeyHex = "c8033fb505790f104a9d69cf26f4ce299fde92f65461b12d2603788461c9ffe7"

// selfServePublicKeyHex is the SELF-SERVE signing key's public half. Its
// private key lives in the activation service (docs/design/
// activation-service.md), which is online by necessity — key separation caps
// the blast radius of a service compromise at "can mint Pro", never
// Enterprise. If it leaks: drop this constant in a release and re-issue
// affected Pro customers from a fresh pair; the master key is unaffected.
const selfServePublicKeyHex = "8346c7c3be7413ff7d3247549508db0bde5f7ba24e28f1d4187410d4e584bf8b"

var embeddedPublicKey = mustHex(publicKeyHex)
var embeddedSelfServeKey = mustHex(selfServePublicKeyHex)

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil || len(b) != 32 {
		panic("licensing: embedded public key is malformed")
	}
	return b
}
