# CodeDistill SERVER RPM (Fedora/RHEL) — multi-user, Postgres-backed.
#
# Unlike the desktop `codedistill` package (single-user, SQLite, systemd USER
# unit), this is a system service: it Requires Postgres, auto-provisions it on
# install (role + database + connection string via peer/socket auth), and runs
# as a dedicated `codedistill` system user. Built by build-server-rpm.sh.

%global debug_package %{nil}

Name:       codedistill-server
Version:    %{_version}
Release:    1%{?dist}
Summary:    CodeDistill multi-user server (Postgres-backed)

License:    Proprietary
URL:        https://github.com/codedistill/codedistill
Source0:    %{name}-%{version}.tar.gz

# Pure-Go binary: pgx is pure Go too, so there is still no library dependency.
# The dependency is a RUNNING Postgres SERVER, which we pull in + provision.
AutoReqProv: no
BuildArch:  x86_64

Requires:        postgresql-server
Requires(post):  postgresql-server
Requires(post):  shadow-utils
Requires(post):  systemd
# The Ollama provisioner downloads the installer + probes the local API.
Requires(post):  curl
Requires(preun): systemd
Requires(postun): systemd

# The desktop and server packages both install /opt/CodeDistill — pick one.
Conflicts:  codedistill

%description
CodeDistill server: the multi-user, Postgres-backed deployment. Installing this
package pulls in Postgres and provisions it hands-off (a codedistill role +
database, reachable over the local socket), installs Ollama with a model sized
to the machine's RAM, then you place a Pro/Enterprise license and start the
service.

For the single-user desktop install (SQLite, no server), use the `codedistill`
package instead.

%prep
%setup -q

%build
:

%install
mkdir -p %{buildroot}/opt/CodeDistill/bin
install -m 0755 codedistill %{buildroot}/opt/CodeDistill/bin/codedistill

mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 codedistill-server.service %{buildroot}/usr/lib/systemd/system/codedistill-server.service

mkdir -p %{buildroot}/opt/CodeDistill/libexec
install -m 0755 provision-postgres.sh %{buildroot}/opt/CodeDistill/libexec/provision-postgres.sh
install -m 0755 provision-ollama.sh %{buildroot}/opt/CodeDistill/libexec/provision-ollama.sh

mkdir -p %{buildroot}/etc/profile.d
install -m 0644 codedistill-profile.sh %{buildroot}/etc/profile.d/codedistill.sh

mkdir -p %{buildroot}/usr/share/doc/%{name}
install -m 0644 README.txt %{buildroot}/usr/share/doc/%{name}/README

%files
%dir /opt/CodeDistill
%dir /opt/CodeDistill/bin
%dir /opt/CodeDistill/libexec
/opt/CodeDistill/bin/codedistill
/opt/CodeDistill/libexec/provision-postgres.sh
/opt/CodeDistill/libexec/provision-ollama.sh
/etc/profile.d/codedistill.sh
/usr/lib/systemd/system/codedistill-server.service
%doc /usr/share/doc/%{name}/README

%post
# Auto-provision Postgres, then Ollama + a RAM-sized model (both idempotent).
# Non-fatal: a provisioning hiccup shouldn't fail the package install — print
# how to re-run it.
/opt/CodeDistill/libexec/provision-postgres.sh || \
  echo "codedistill-server: provisioning incomplete — re-run /opt/CodeDistill/libexec/provision-postgres.sh after Postgres is up"
/opt/CodeDistill/libexec/provision-ollama.sh || \
  echo "codedistill-server: Ollama setup incomplete — re-run /opt/CodeDistill/libexec/provision-ollama.sh"
%systemd_post codedistill-server.service

%preun
%systemd_preun codedistill-server.service

%postun
%systemd_postun_with_restart codedistill-server.service
# Leave the database, role, blob dir, and env file in place on uninstall — data
# is the operator's, not ours to delete.

%changelog
* %{_changelog_date} CodeDistill <noreply@codedistill.dev> - %{_version}-1
- Auto-generated by build-server-rpm.sh — see CHANGELOG.md for details.
